### ISSUE TITLE
Ability to `--skip-shell` for fnm

### ISSUE THREAD

**Issue by bentruyman** [Schniz/homebrew-tap#1]
Would it be possible to add an optional flag (e.g. `--skip-shell`) which forces skipping the shell profile update?

For example, [I have fnm already configured](https://github.com/bentruyman/dotfiles/blob/2c46f8e7bcb148391eb6fac980458fa6530b73a4/files/lib/nodejs.zsh#L5) in a `nodejs.zsh` file which is loaded via `.zshrc` — but the current formula will always update `.zshrc` as no line with `# fnm` exists in it. It would be nice to have for those of us with slightly complicated dotfiles setups.

**Comment by davidosomething** [comment]
2nded, zsh supports a custom `$ZDOTDIR`, which defined in your `.zshenv` allows you to put your `.zshrc` outside of $HOME. The `shell_profile` util does not understand this

**Comment by Schniz** [comment]
This would be nice. I'd accept a PR doing that. I have no knowledge in Homebrew's DSL, feel free to dive in and share with us!
