### ISSUE TITLE
[Feature Request]: Add Linux support

### ISSUE THREAD

**Issue by dalisoft** [Schniz/homebrew-tap#10]
Hi @Schniz

Thanks for such a great work, i really love `fnm`, it's lighting fast (when combine it with alias, it's unbeatable performance).
Currently i making own dotfiles, apps sync repo with ansible, but seems **fnm** does install only on macOS with Homebrew according this this [line](https://github.com/Schniz/homebrew-tap/blob/master/Formula/fnm.rb#L10)

Are you planning add Linux support? It would be great, i am not know Homebrew taps good enough, but sometime i will try

Thanks

**Comment by dalisoft** [comment]
Sorry for wrong issue, today installing and tested on Ubuntu 20.04, works fine

**Comment by Schniz** [comment]
No biggie. Thanks for using fnm! Have fun 😁
