### ISSUE TITLE
Move formula to main Homebrew repository

### ISSUE THREAD

**Issue by waldyrious** [Schniz/homebrew-tap#12]
The README says that this formula will eventually be moved to `homebrew-core`, so I thought I'd create an issue to track this, which IMO will fulfill the original vision of https://github.com/Schniz/fnm/issues/5. The prerequisites for that migration to happen, AFAIK, are as follows:

- [x] Project should be [sufficiently notable](https://github.com/Homebrew/brew/blob/c9fac7c2892ac4f100666c8eb7209da3f20b8def/Library/Homebrew/utils/notability.rb#L37) (as pointed out in thee previous submission at https://github.com/Homebrew/homebrew-core/pull/36744)
- [ ] Formula should build the project from source
- [ ] Formula should pass `brew audit` (looks like #9 does this?)

**Comment by Schniz** [comment]
https://github.com/Homebrew/homebrew-core/pull/63459

Let's hope it gets accepted this time 😄

**Comment by ghost** [comment]
@Schniz, the pull request was accepted and merged, so this issue can be closed.

~One thing, though, is that `v1.22.3` (currently the latest version) has not been added to core yet.~

Edit:
It appears someone added `v1.22.3` to `homebrew/core` tonight 😊 

Also, as GitHub recently migrated their CLI tool, I noticed that there's a useful deprecation feature you can add to this repository. You can find the PR made on their repository [here](https://github.com/github/homebrew-gh/pull/13). For automated releases, you can also take a look at [their automated homebrew release](https://github.com/cli/cli/blob/v1.2.0/.github/workflows/releases.yml#L156-L162) as well. If you would like, I could make a PR here for the tap deprecation warning and a PR in fnm's main repository for the automated release. This would be new for me with automated homebrew setup, but I would be happy to do it. 🙂
